name: build
on:
  push:
    paths-ignore:
      - "README.md"
      - "art/**"
  pull_request:
    paths-ignore:
      - "README.md"
      - "art/**"
jobs:
  buildJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: chmod +x gradlew

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Creating required files
        run: |
          echo ${{secrets.SIGNING_KEY}} > key.jks.base64
          echo ${{secrets.PLAY_CONFIG}} > play_config.json.base64

          base64 -d -i key.jks.base64 > key.jks
          base64 -d -i play_config.json.base64 > play_config.json

          echo signing.alias=${{secrets.ALIAS}} >> local.properties
          echo signing.storePassword=${{secrets.STORE_PASSWORD}} >> local.properties
          echo signing.keyPassword=${{secrets.KEY_PASSWORD}} >> local.properties
          echo signing.keyFile=key.jks >> local.properties

      - name: Assemble & Sign
        run: |
          ./gradlew app:assembleRelease --stacktrace
